# Generated by Django 3.2.5 on 2021-07-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0010_auto_20210410_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='rating',
            field=models.TextField(blank=True, null=True),
        ),
    ]
