# Generated by Django 3.2.5 on 2021-07-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0011_comments_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Image1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='Image2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='Image3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='Video',
        ),
    ]
